# Домашняя работа
# Исключения и обработка ошибок
### Задача №1
Функция function() была вынесена в файл functions.cpp с заголовочным файлом functions.h. Исключение bad_length было создано в отдельном классе, унаследованном от std::exception.
### Задача №2
Был создан класс исключения FigureError. Проверка на исключение выполняется при создании экземпляра класса (наследника класса Figure) во время вызова из конструктора метода tryException().

Работу выполнил Олег Нечибыло.